spring:
  config:
    import:
      - classpath:dev-db-h2.yml
      - classpath:./config/secret-dev.yml

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        show_sql: false

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  access-token-validity-time: 18000000 # 300분
  refresh-token-validity-time: 60480000 # 1008분
