# ??: https://velog.io/@backtony/JPA-%ED%99%9C%EC%9A%A91-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%ED%99%98%EA%B2%BD%EC%84%A4%EC%A0%95

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:myomeet
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace