# Copyright 2020 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: MyohanMeeting Backend CICD

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_INSTANCE: myoback-dev
  GCE_INSTANCE_ZONE: us-central1-a
  SSH_DIR: ${{ secrets.SSH_DIR }}
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/myoback-dev:latest


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Secret
        run: |-
          mkdir ./MyohanMeeting/src/main/resources/config
          touch ./MyohanMeeting/src/main/resources/config/secret-dev.yml
          echo "${{ secrets.DEV_SECRET_PROPERTIES_H2 }}" > ./MyohanMeeting/src/main/resources/config/secret-dev.yml
          cat ./MyohanMeeting/src/main/resources/config/secret-dev.yml

      - name: Create Google Cloud Storage Key
        run: |-
          touch ./MyohanMeeting/src/main/resources/config/cloud-storage-key.json
          echo "${{ secrets.GCS_SA_KEY }}" > ./MyohanMeeting/src/main/resources/config/cloud-storage-key.json
          cat ./MyohanMeeting/src/main/resources/config/cloud-storage-key.json

      - name: Create SSH Key
        run: |-
          touch $SSH_DIR.pub
          echo "${{ secrets.GCP_SSH_PUB }}" > $SSH_DIR.pub
          chmod 400 $SSH_DIR.pub
          touch $SSH_DIR
          echo "${{ secrets.GCP_SSH_KEY }}" > $SSH_DIR
          chmod 400 $SSH_DIR

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag $IMAGE_NAME /home/runner/work/MeMyo-Backend/MeMyo-Backend/MyohanMeeting
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push $IMAGE_NAME
      - name: Deploy
        run: |-
          gcloud compute ssh --project=$PROJECT_ID --zone=$GCE_INSTANCE_ZONE $GCE_INSTANCE \
            --ssh-key-file=$SSH_DIR \
            --command="sudo gcloud --quiet auth activate-service-account ${{ secrets.GCE_SA_EMAIL }} --key-file=${{ secrets.GCE_SA_KEY_DIR }}
              sudo gcloud --quiet auth configure-docker gcr.io
              cd ${{ secrets.PROJ_DIR }}
              sudo docker compose down
              sudo docker rmi $IMAGE_NAME -f
              sudo docker compose up -d"
